name: flutter_ioioksdk
description: "flutter version of IOIOKSDK."
version: 0.0.3
homepage: https://github.com/fuzhu666/IOIOKSDK

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_ioioksdk
        pluginClass: FlutterIoioksdkPlugin
      ios:
        pluginClass: FlutterIoioksdkPlugin
